# -*- coding: utf-8 -*-
"""ATLAS_PAPER_GLUE_OBLIGATIONS_AND_GENERATORS: the two placeholders of the atlas paper, §4.3 (gluing obligations) and
§5.3 (transition generators), DERIVED rather than asserted. Read-only, exact arithmetic (Fraction + finite graphs).
No heavy computation. Concerns the atlas paper only; it does not affect any other part of the verification tree.

MODEL (re-read from the sources, not re-postulated): μ = (1,2,3,5,7,11); F_k = Σ_j μ_j^k z_j², k = 0,1,2;
X = {F₀ = F₁ = F₂ = 0} ⊂ P⁵. The quadrics are LINEAR in the squares w_j = z_j²: writing V_full = (μ_j^k) for the 3×6
matrix of exponents, the variety imposes V_full·w = 0.

(A) THE COCYCLE OF SQUARES, EXACT. For a triple S and its complement T: V_S w_S + V_T w_T = 0 ⇒ w_T = −V_T^{-1}V_S w_S
    (V_S is a Vandermonde matrix in (μ_s), NONSINGULAR because the μ are pairwise distinct — derived over all 20 triples).
    Hence w_S determines the whole of w, and for every ordered pair (S,S′) there is a RATIONAL 3×3 matrix P_{S′S} with
    w_{S′} = P_{S′S} w_S on X. Derived here: P_{SS} = I (20/20); P_{SS′}P_{S′S} = I (400/400); **the cocycle identity
    P_{S″S′}P_{S′S} = P_{S″S} on all 8000 ordered triples, in exact arithmetic**. This is the algebraic foundation of
    §5.2 (the certified panel, 3540/3540, is its counterpart on the side of applicability over the domain). The constant
    of the radical atlas is re-derived: C = max_S ‖V_S^{-1}V_T‖_∞ = **exactly 112** (infinity norm = maximum of the row
    sums; attained at S = (0,1,2)), with max |entry| = 80.

(B) GENERATORS (§5.3). Chart types (S,g) with g ∉ S: **60** of them (20 triples × 3 gauges). Two elementary moves:
      · ELEMENTARY SWAP: S → S′ with |S ∩ S′| = 2 (one solved coordinate is exchanged for one base coordinate);
      · GAUGE CHANGE: (S,g) → (S,g′) with g′ ∈ T∖{g} (projective rescaling by z_{g′}/z_g).
    Derived: the Johnson graph J(6,3) on the triples has **20 vertices, 90 edges, is connected, and has diameter 3**;
    the graph on the **60 types** under {swap at CONSTANT gauge, gauge change at CONSTANT S} is **connected with
    diameter 4** (the earlier 3 came from a COMPOSITE swap; witness: (012,3) -> (024,3) -> (024,1) -> (234,1) ->
    (345,1)). Together with the cocycle of (A),
    connectedness yields GENERATION: **every transition is a word of length ≤ 4 in {elementary swap, gauge change},
    composed with a sheet flip** (the diameter BOUNDS the word length — that is the quantitative content of the
    proposition). Discriminating check: WITHOUT the gauge changes, the graph on types **breaks into 6 components of 10**
    (one per frozen gauge: S then ranges over J(5,3) on the 5 coordinates ≠ g), so the gauge moves are NECESSARY rather
    than decorative.

(C) THE DECK GROUP, IN NUMBERS (§6.2/§6.3). Diagonal sign matrices preserve each quadric, since the coordinates enter
    only through their squares: {±1}⁶ modulo the projective scalar ±1 gives a group of **order 32**, generated by 5
    flips. For a fixed type (S,g), an element is VERTICAL (it moves the sheet only and fixes the base point) if and only
    if δ is constant on T = the complement of S: this gives a **vertical subgroup of order 8, of INDEX 4**, the quotient
    (Z/2)² moving the base point. Exact instance for D = diag(+1,−1,+1,+1,+1,−1) (the deck element measured on the
    bridges): D is vertical for exactly **4 triples, i.e. 12 types out of 60**, and moves the base point on the other
    **48** — this is §6.3, "abstract deck action ≠ vertical action chart by chart", in numbers.

(D) THE SIX GLUING OBLIGATIONS (§4.3), CLASSIFIED. X_atlas = (⊔_α U_α)/∼, with Φ : X_atlas → X ⊂ P⁵ tautological
    chart by chart.
    O1 ∼ is an equivalence relation     ← exact cocycle (A) + P_{SS} = I + inverses [EXACT ALGEBRA, checked here]
    O2 Φ is well defined                ← each chart lands in X (the sections solve F₀ = F₁ = F₂ = 0) [EXACT ALGEBRA]
    O3 Φ is a local biholomorphism      ← Prop. 3.1 (certified radius ρ_unif) [CERTIFICATE U1]
    O4 Φ is surjective                  ← the pivot open sets cover X (τ = 0.6) [COVERING CERTIFICATE]
    O5 Φ is injective                   ← ∼ captures ALL coincidences: two chart points with the same projective image
                                           are related by a transition — this is the role of the sheet record (exactly
                                           one sheet per point: 8 exhaustive sheets) [EXACT ALGEBRA + SHEET RECORD]
    O6 X_atlas is second countable      ← the atlas is FINITE by compactness; a continuous bijection that is a local
       and Hausdorff                       homeomorphism is open, hence a homeomorphism, so X_atlas inherits the
                                           topology of X [TOPOLOGY + finiteness]. Separation is NOT bought with an
                                           estimate: the former "Hausdorff by certified margin" obligation is gone.
    Distribution derived here: 3 obligations of exact algebra (O1, O2, O5 — the last with the exhaustive sheet record),
    2 certificates (O3, O4), 1 topological (O6). The sheet record is consumed by O5 ONLY; no obligation consumes a
    separation margin. The `reading` field of the certificate is built FROM these modes, not written by hand.
Negative controls: N1 repeated μ = (1,1,3,5,7,11) ⇒ V_S = 0 for S ⊇ {0,1} ⇒ the transitions cease to exist (check Q1
fails); N2 gauge moves removed ⇒ 6 components ⇒ generation fails (check Q4); N3 one entry of P mutated ⇒ the cocycle
fails (check Q2).
Does not attest: the certified panel itself (3540/3540, margins, ρ_unif — produced upstream and re-read here through
their artifacts); the covering (D3); the geometry of the bridges (the bridge step); O6/O7 as complete topological proofs (the
certified inputs are named, the argument is written out in the paper); anything outside the atlas paper.
"""
from __future__ import annotations

import hashlib
import io
import json
import sys
import time
from collections import deque
from fractions import Fraction as Fr
from itertools import combinations
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

HERE = Path(__file__).resolve()
ROOT = HERE.parents[2]
RES = ROOT / "certificates"
U1 = RES / "open_chart_theorem.json"
T2 = RES / "quantitative_atlas.json"
BRIDGE = RES / "bridge_atlas_panel.json"
OUT = RES / "glue_obligations.json"

MU_DEFAULT = (1, 2, 3, 5, 7, 11)
D_DECK = (1, -1, 1, 1, 1, -1)


def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def load(p): return json.loads(p.read_text(encoding="utf-8"))


def det3(M):
    return (M[0][0] * (M[1][1] * M[2][2] - M[1][2] * M[2][1])
            - M[0][1] * (M[1][0] * M[2][2] - M[1][2] * M[2][0])
            + M[0][2] * (M[1][0] * M[2][1] - M[1][1] * M[2][0]))


def inv3(M):
    d = det3(M)
    C = [[Fr(0)] * 3 for _ in range(3)]
    for i in range(3):
        for j in range(3):
            m = [[M[a][b] for b in range(3) if b != j] for a in range(3) if a != i]
            C[j][i] = Fr((-1) ** (i + j)) * (m[0][0] * m[1][1] - m[0][1] * m[1][0]) / d
    return C


def mul(A, B):
    return [[sum(A[i][k] * B[k][j] for k in range(3)) for j in range(3)] for i in range(3)]


def eye():
    return [[Fr(1) if i == j else Fr(0) for j in range(3)] for i in range(3)]


def bfs(adj, src):
    d = {src: 0}
    q = deque([src])
    while q:
        x = q.popleft()
        for y in adj[x]:
            if y not in d:
                d[y] = d[x] + 1
                q.append(y)
    return d


def build(mutate=None):
    mutate = mutate or {}
    t0 = time.time()
    mu = (1, 1, 3, 5, 7, 11) if "mu_repeat" in mutate else MU_DEFAULT
    tri = list(combinations(range(6), 3))
    Vm = lambda S: [[Fr(mu[s]) ** k for s in S] for k in range(3)]
    dets = {S: det3(Vm(S)) for S in tri}
    all_pivots_nonzero = all(d != 0 for d in dets.values())
    # ---- (A) cocycle of the squares + constant C ------------------------------------------------------------------------
    P, C_inf, C_arg, max_entry = {}, Fr(0), None, Fr(0)
    if all_pivots_nonzero:
        # w_full from w_S: w_S = w_S, w_T = −V_T^{-1} V_S w_S  →  columns indexed by S
        full = {}
        for S in tri:
            T = tuple(t for t in range(6) if t not in S)
            MTS = mul(inv3(Vm(T)), Vm(S))
            MTS = [[-x for x in row] for row in MTS]                       # w_T = −V_T^{-1}V_S w_S
            W = {}
            for i, s in enumerate(S):
                W[s] = [Fr(1) if j == i else Fr(0) for j in range(3)]
            for i, t in enumerate(T):
                W[t] = MTS[i]
            full[S] = W                                                     # w_j = W[j] · w_S
            row_sums = [sum(abs(x) for x in row) for row in mul(inv3(Vm(S)), Vm(T))]
            if max(row_sums) > C_inf:
                C_inf, C_arg = max(row_sums), (S, T)
            max_entry = max([max_entry] + [abs(x) for row in mul(inv3(Vm(S)), Vm(T)) for x in row])
        for S in tri:
            for S2 in tri:
                P[(S2, S)] = [full[S][s2] for s2 in S2]                     # w_{S2} = P[(S2,S)] w_S
        if "mutate_P" in mutate:
            k = (tri[1], tri[0])
            P[k] = [list(r) for r in P[k]]
            P[k][0][0] = P[k][0][0] + 1
    identity_ok = all_pivots_nonzero and all(P[(S, S)] == eye() for S in tri)
    inverse_ok = all_pivots_nonzero and all(mul(P[(S2, S)], P[(S, S2)]) == eye() for S in tri for S2 in tri)
    cocycle_n = cocycle_ok_n = 0
    if all_pivots_nonzero:
        for S in tri:
            for S2 in tri:
                for S3 in tri:
                    cocycle_n += 1
                    if mul(P[(S3, S2)], P[(S2, S)]) == P[(S3, S)]:
                        cocycle_ok_n += 1
    cocycle_ok = cocycle_n > 0 and cocycle_ok_n == cocycle_n
    # ---- (B) type graphs and generation ----------------------------------------------------------------------------------
    adjJ = {S: [S2 for S2 in tri if len(set(S) & set(S2)) == 2] for S in tri}
    edgesJ = sum(len(v) for v in adjJ.values()) // 2
    dJ = [bfs(adjJ, S) for S in tri]
    J_connected = all(len(d) == len(tri) for d in dJ)
    J_diam = max(max(d.values()) for d in dJ) if J_connected else None
    types = [(S, g) for S in tri for g in range(6) if g not in S]
    gauge_on = "no_gauge_moves" not in mutate

    def nbrs(t, gauge=True):
        # THE TWO GENERATORS OF THE PAPER, AND NOTHING ELSE.
        # The swap loop used to accept any g2 compatible with S2, that is a
        # swap AND a gauge change in ONE step. That composite move has
        # diameter 3; the two generators as stated in section 5.1 have
        # diameter 4 (witness: (012,3) -> (024,3) -> (024,1) -> (234,1) ->
        # (345,1)). The word-length bound must be about the PUBLISHED
        # generators. The negative control also used to redefine the swap
        # instead of removing gauge changes, so it did not test what it claimed.
        S, g = t
        out = set()
        for S2 in adjJ[S]:                      # elementary swap, g CONSTANT
            if g not in S2:
                out.add((S2, g))
        if gauge:                               # gauge change, S CONSTANT
            for g2 in range(6):
                if g2 not in S and g2 != g:
                    out.add((S, g2))
        out.discard(t)
        return list(out)

    adjT = {t: nbrs(t, gauge_on) for t in types}
    dT = [bfs(adjT, t) for t in types]
    T_connected = all(len(d) == len(types) for d in dT)
    T_diam = max(max(d.values()) for d in dT) if T_connected else None
    comps, seen = 0, set()
    comp_sizes = []
    for t in types:
        if t in seen:
            continue
        d = bfs(adjT, t)
        seen |= set(d)
        comps += 1
        comp_sizes.append(len(d))
    # ---- (C) deck group ----------------------------------------------------------------------------------------------------
    deck_order = 2 ** 6 // 2
    def vertical_for(delta, t):
        S, g = t
        T = [x for x in range(6) if x not in S]
        return len(set(delta[i] for i in T)) == 1
    vert_types_generic = [t for t in types if vertical_for((1, 1, 1, 1, 1, 1), t)]           # all types are vertical for the identity
    D_vert_types = [t for t in types if vertical_for(D_DECK, t)]
    D_vert_triples = sorted(set(t[0] for t in D_vert_types))
    # vertical subgroup of a fixed type: δ constant on T, δ|_S free, modulo ±1
    t0_type = types[0]
    S0, g0 = t0_type
    T0 = [x for x in range(6) if x not in S0]
    verts = set()
    for bits in range(64):
        delta = tuple(1 if (bits >> i) & 1 == 0 else -1 for i in range(6))
        if len(set(delta[i] for i in T0)) == 1:
            canon = delta if delta[0] == 1 else tuple(-x for x in delta)
            verts.add(canon)
    vert_order = len(verts)
    index = deck_order // vert_order if vert_order else None
    # ---- (D) classified obligations --------------------------------------------------------------------------------------
    obligations = [
        {"id": "O1", "claim": "∼ is an equivalence relation", "mode": "EXACT_ALGEBRA",
         "support": "cocycle P_{S″S′}P_{S′S} = P_{S″S} + P_{SS} = I + inverses (all checked here)"},
        {"id": "O2", "claim": "Φ is well defined (each chart lands in X)", "mode": "EXACT_ALGEBRA",
         "support": "the sections solve F₀ = F₁ = F₂ = 0 by construction (elimination)"},
        {"id": "O3", "claim": "Φ is a local biholomorphism", "mode": "CERTIFICATE",
         "support": "Prop. 3.1 / U1: certified radius ρ_unif, contraction h < 1/2"},
        {"id": "O4", "claim": "Φ is surjective", "mode": "CERTIFICATE",
         "support": "the pivot open sets cover X (margin τ = 0.6)"},
        {"id": "O5", "claim": "Φ is injective", "mode": "EXACT_ALGEBRA_PLUS_LEDGER",
         "support": "8 exhaustive signed sheets: a point of X matches exactly one sheet record entry, so ∼ captures every coincidence"},
        # O6 MERGES the former O6/O7 pair and changes MODE. The old O6
        # "Hausdorff" was a CERTIFICATE: it bought separation with a numerical
        # margin. The paper has since established that it is not bought that
        # way — a continuous bijection that is a LOCAL homeomorphism is open,
        # hence a homeomorphism, and X_atlas then inherits the topology of X.
        {"id": "O6", "claim": "X_atlas is second countable and Hausdorff",
         "mode": "TOPOLOGY_FINITENESS",
         "support": "the atlas is finite by compactness of X; a continuous "
                    "bijection that is a local homeomorphism is open, hence a "
                    "homeomorphism: X_atlas inherits the topology of X"}]
    n_alg = sum(1 for o in obligations if o["mode"].startswith("EXACT_ALGEBRA"))
    n_cert = sum(1 for o in obligations if o["mode"] == "CERTIFICATE")
    n_top = sum(1 for o in obligations if o["mode"] == "TOPOLOGY_FINITENESS")
    # ---- upstream artifacts (re-read, never rewritten) ---------------------------------------------------------------------
    u1 = load(U1) if U1.exists() else {}
    t2 = load(T2) if T2.exists() else {}
    br = load(BRIDGE) if BRIDGE.exists() else {}
    upstream_ok = (str(u1.get("outcome", "")).startswith("uniform_open_chart_theorem")
                   and str(t2.get("outcome", "")).startswith("t2_fixed_k3_closed")
                   and bool(br))
    out = {"artifact": "glue_obligations",
           "subject": "ATLAS PAPER §4.3 + §5.3 — exact cocycle of the squares (8000 ordered triples), C = 112 re-derived, "
                  "graph on the 60 types connected with diameter 4, hence generation by {elementary swap, gauge} plus a "
                  "sheet flip (words of length ≤ 4), deck group of order 32 with vertical subgroup of index 4, six "
                  "gluing obligations classified",
           "kind": "exact_algebra_and_finite_graphs", "stage": "atlas paper (no other part of the tree is affected)",
           "no_measurement_performed": "exact rational algebra + finite graph theory", "nothing_is_rewritten": True,
           "upstream": {"u1": sha(U1) if U1.exists() else None, "u1_outcome": u1.get("outcome"),
                        "t2": sha(T2) if T2.exists() else None, "t2_outcome": t2.get("outcome"),
                        "bridge_panel": sha(BRIDGE) if BRIDGE.exists() else None},
           "A_square_cocycle": {"mu": list(mu), "n_triples": len(tri), "all_vandermonde_nonzero": bool(all_pivots_nonzero),
                                "P_SS_is_identity": bool(identity_ok), "P_inverse_pairs_ok": bool(inverse_ok),
                                "cocycle_checked": cocycle_n, "cocycle_ok": cocycle_ok_n, "cocycle_all_ok": bool(cocycle_ok),
                                "C_inf_norm": str(C_inf), "C_argmax": [list(C_arg[0]), list(C_arg[1])] if C_arg else None,
                                "max_abs_entry": str(max_entry),
                                "reading": "algebraic foundation of §5.2; the certified panel 3540/3540 is its counterpart on the side of applicability over the domain"},
           "B_generators": {"n_types": len(types), "johnson_J63": {"nodes": len(tri), "edges": edgesJ, "connected": bool(J_connected), "diameter": J_diam},
                            "type_graph": {"nodes": len(types), "connected": bool(T_connected), "diameter": T_diam,
                                           "components": comps, "component_sizes": sorted(set(comp_sizes))},
                            "generators": ["elementary swap (|S ∩ S′| = 2)", "gauge change (S,g) → (S,g′)", "sheet flip (diagonal deck element)"],
                            "word_length_bound": T_diam,
                            "statement": "cocycle (A) + connectedness ⇒ every transition is a word of length ≤ diam in {swap, gauge}, composed with a sheet flip",
                            "gauge_moves_necessary": "without gauge moves: 6 components of 10 (negative control N2)"},
           "C_deck": {"order": deck_order, "generators": 5, "vertical_subgroup_order": vert_order, "vertical_index": index,
                      "base_quotient": "(Z/2)² moves the base point",
                      "D": list(D_DECK), "D_vertical_types": len(D_vert_types), "D_vertical_triples": len(D_vert_triples),
                      "D_base_moving_types": len(types) - len(D_vert_types),
                      "reading": "§6.3 in numbers: the same abstract transformation is vertical for 12 types out of 60 and moves the base point on the other 48"},
           "D_glue_obligations": {"obligations": obligations, "n_exact_algebra": n_alg, "n_certificate": n_cert, "n_topology": n_top,
                                  "reading": (f"{n_alg} obligations of exact algebra ({', '.join(o['id'] for o in obligations if o['mode'].startswith('EXACT_ALGEBRA'))}; "
                                              f"O5 consumes the exhaustive sheet record), {n_cert} certificates "
                                              f"({', '.join(o['id'] for o in obligations if o['mode'] == 'CERTIFICATE')}), "
                                              f"{n_top} topological ({', '.join(o['id'] for o in obligations if o['mode'] == 'TOPOLOGY_FINITENESS')}: "
                                              "finiteness and open bijection — separation is not bought with an estimate)")},
           "does_not_attest": ["the certified panel itself (3540/3540, margins, ρ_unif — produced upstream)", "the covering D3",
                             "the geometry of the bridges (the bridge step)", "O6/O7 as complete topological proofs (inputs named, argument written out in the paper)",
                             "anything outside the atlas paper"]}
    g = {"Q1_vandermonde_all_nonzero_and_transitions_exist": bool(all_pivots_nonzero) and bool(identity_ok),
         "Q2_square_cocycle_exact_on_all_ordered_triples": bool(cocycle_ok) and cocycle_n == len(tri) ** 3 and bool(inverse_ok),
         "Q3_radical_constant_C_112_rederived": all_pivots_nonzero and C_inf == 112 and max_entry == 80,
         "Q4_type_graph_connected_bounds_word_length": bool(T_connected) and T_diam == 4 and len(types) == 60,
         "Q5_johnson_J63_20_90_connected_diam3": bool(J_connected) and len(tri) == 20 and edgesJ == 90 and J_diam == 3,
         "Q6_deck_order32_vertical_index4_D_split_12_48": (deck_order == 32 and vert_order == 8 and index == 4
                                                           and len(D_vert_types) == 12 and len(D_vert_triples) == 4),
         "Q7_six_obligations_typed_3_2_1": (len(obligations) == 6 and n_alg == 3 and n_cert == 2 and n_top == 1),
         "Q8_upstream_certificates_read": bool(upstream_ok)}
    out["checks"] = {k: bool(v) for k, v in g.items()}
    out["checks_passed"] = sum(bool(v) for v in g.values()); out["checks_total"] = len(g)
    out["outcome"] = "atlas_paper_glue_obligations_typed_and_transition_generators_derived_word_length_le_4" if all(g.values()) else "atlas_paper_checks_red"
    out["seconds"] = round(time.time() - t0, 1)
    return out


def main():
    out = build()
    st = {"N1_mu_repeat_kills_transitions": not build(mutate={"mu_repeat"})["checks"]["Q1_vandermonde_all_nonzero_and_transitions_exist"],
          "N2_no_gauge_moves_disconnects_type_graph": not build(mutate={"no_gauge_moves"})["checks"]["Q4_type_graph_connected_bounds_word_length"],
          "N3_mutated_P_entry_breaks_cocycle": not build(mutate={"mutate_P"})["checks"]["Q2_square_cocycle_exact_on_all_ordered_triples"]}
    out["perturbation_tests"] = st; out["perturbation_tests_passed"] = sum(bool(v) for v in st.values()); out["perturbation_tests_total"] = len(st)
    try:
        import subprocess
        out["built_from_head"] = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
    except Exception:
        out["built_from_head"] = None
    out["self_sha256"] = sha(HERE)
    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=1), encoding="utf-8")
    print(f"checks {out['checks_passed']}/{out['checks_total']} · self-tests {out['perturbation_tests_passed']}/{out['perturbation_tests_total']} · {out['seconds']} s")
    for k, v in out["checks"].items(): print(f"  {'OK ' if v else 'RED'} {k}")
    for k, v in out["perturbation_tests"].items(): print(f"  {'OK ' if v else 'RED'} {k}")
    a, b, c = out["A_square_cocycle"], out["B_generators"], out["C_deck"]
    print(f"cocycle {a['cocycle_ok']}/{a['cocycle_checked']} | C = {a['C_inf_norm']} (max entry {a['max_abs_entry']}) | "
          f"types {b['n_types']} diam {b['type_graph']['diameter']} | deck {c['order']}, vertical {c['vertical_subgroup_order']} (index {c['vertical_index']}), D: {c['D_vertical_types']}/{b['n_types']} vertical")
    print("outcome:", out["outcome"])


if __name__ == "__main__":
    main()
